permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 张泽	
  email: chnzhn86@gmail.com
  link: http://zdx.link
  weibo: http://weibo.com/iamzhangze
  github: http://github.com/zdx86

# 站点信息
title: 张大侠的博客 
description: 张大侠的博客
url: http://zdx.link
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xl7o9.com1.z0.glb.clouddn.com/zdxdanbo.jpg
favicon: http://7xl7o9.com1.z0.glb.clouddn.com/zdxfavicon.png.png

# google analytics 设置
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# disqus 设置
disqus:
  shortname: zdx.it
